apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: openmetricsrules.open-metrics.vgs.io
spec:
  group: open-metrics.vgs.io
  names:
    plural: openmetricsrules
    singular: openmetricsrule
    kind: OpenMetricsRule
    listKind: OpenMetricsRuleList
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: >-
                OpenMetricsRule CRD contains specification parameters for a
                Rule.
              required:
                - tenants
              properties:
                description:
                  type: string
                groups:
                  description: Content of Open Metrics rule file
                  type: array
                  items:
                    type: object
                    description: >-
                      RuleGroup is a list of sequentially evaluated recording
                      and alerting rules.
                    required:
                      - name
                      - rules
                    properties:
                      interval:
                        type: string
                      name:
                        type: string
                      rules:
                        type: array
                        items:
                          type: object
                          description: >-
                            Open Metrics Rule describes an alerting or recording
                            rule.
                          required:
                            - expr
                          properties:
                            alert:
                              type: string
                            annotations:
                              type: object
                            expr:
                              type: string
                            for:
                              type: string
                            labels:
                              type: object
                            record:
                              type: string
                tenants:
                  type: array
                  items:
                    type: string
  conversion:
    strategy: None
  preserveUnknownFields: true
